Fix issue #71 & #78
The-Marquis-Gaming/themarquis-ui-sc pull request #86
Opened 2024-11-26 18:50 UTC by HungNDB

# Resolve Issue
Fixes #71 & #78
## Types of change

- [x] Feature
- [x] Bug
- [x] Enhancement

2024-11-27 09:12 UTC, Buuh2511 requested changes
Refactor mainly on [file ](packages/nextjs/app/brandkit/page.tsx)

2024-11-27 09:12 UTC, Buuh2511 commented on packages/nextjs/app/brandkit/page.tsx
> +            <div className="sm:mb-[92px] mb-[50px] sm:text-[36px] text-[24px] text-gradient-2 text-[#00ECFF] font-bold font-arial">
Could u plse refactor this

2024-11-28 03:01 UTC, Buuh2511 approved these changes

2024-11-28 03:04 UTC, merged

2024-11-28 03:05 UTC, gianalarcon commented
Thanks for your contribution @HungNDB! Please DM on discord: gianalarcon